export const COPY = {
  brand: 'Still On?',
  tagline: 'The vibe check for plans.',
  heroTitle: 'Cancel plans without being the one who cancels.',
  heroBody:
    'If you both secretly want to bail, we tell you both and the plan dies. ' +
    'If only one of you does, nobody ever finds out. No app. No account. Just a link.',
  createCta: 'Start a vibe check',
  titleLabel: 'What is the plan?',
  titlePlaceholder: 'Dinner Friday',
  whenLabel: 'When is it? (optional)',
  voteQuestion: 'Real talk - are you still feeling it?',
  voteOn: 'Still on 😤',
  voteBail: "I'd bail 🏳️",
  votePrivacyNote: 'Your answer stays secret unless you both match.',
  emailLabel: 'Email me the second this resolves (optional)',
  shareHeading: 'Now send them the link',
  shareBody: 'Drop it in the text thread where the plan lives. They answer in one tap.',
  shareButton: 'Share the link',
  copyButton: 'Copy link',
  copied: 'Copied!',
  creatorStatusHeading: 'Waiting on them 👀',
  creatorStatusBody: 'They have not answered yet. You can still change your answer.',
  changeVote: 'Change my answer',
  ownLinkHeading: 'This is your own vibe check 👀',
  ownLinkBody: 'This link is for them, not you. Your private status page is here:',
  cancelledHeading: "🎉 You're BOTH off the hook",
  cancelledBody: (title: string) => `"${title}" is cancelled. Nobody had to be the bad guy.`,
  standsHeading: 'The plan stands 💪',
  standsBody: 'What happens in the vibe check stays in the vibe check. 🤐 See you there.',
  expiredHeading: 'This vibe check expired 🤷',
  expiredBody: 'Nobody answered in time, so the plan stood.',
  startAnother: 'Start your own vibe check',
  inviteeQuestion: (title: string) => `Still on for "${title}"?`,
  shareText: (title: string, url: string) =>
    `Still on for "${title}"? Quick vibe check (your answer stays secret): ${url}`,
  ogTitle: 'Still on? 👀',
  ogSubtitle: 'A vibe check. Your answer stays secret unless you both match.',
  footer: 'Made by Revenue With AI',
  emailSubjectCancelled: "🎉 You're both off the hook",
  emailSubjectStands: 'Vibe check resolved: the plan stands',
} as const;
